### ISSUE TITLE
Issue with the 'Pages' theme

### ISSUE THREAD

**Issue by zman58tmh** [bhadaway/support#6]
I am using the free 'Pages' theme for a non-profit website.  Has an update been released recently for this theme?  The site has been up and running for over 6 months, but in the last week or two an issue arose with the sub-menus on my main menu.  When you hover over one of the menu options that contain sub-menus, the dropdown for the sub-menus open up, but they are hidden behind the page being displayed.  You can see the first option in the sub-menu, but none of the other options.

Here is the url for the site:  www.wipost149.org

You can view the site to see what is happening.  I just wanted to check if something changed recently to cause this or if you have a suggestion for a fix.

Thanks!

**Comment by bhadaway** [comment]
Updated. That should fix it.

**Comment by zman58tmh** [comment]
Hey Bryan, thanks for the update.  Is there anything that I need to do from my end for this fix to go into effect?  I checked the website this morning and it is still having the issue with the sub-menus.

 

You can see this occurring at:  wipost149.org

 

John

**Comment by bhadaway** [comment]
You might need to clear your browser/site caches and refresh the page.

**Comment by zman58tmh** [comment]
Hi Bryan, thanks again for looking into this issue.  Sorry to be a bother but I’ve tried clearing the browser/caches and am still experiencing the same problem.  In fact I tried accessing the site using 2 different browsers (Chrome and Edge) on my laptop and also from a completely different device (a Chromebook) and am experiencing the same problem.  

 

If you view the site (wipost149.org ), are you able to see all of the sub-menus under ‘POST 149 INFO’ and under ‘POST 149 IN ACTION’?  There are 4 sub-menu items under each of these.  When I try on my devices, I can see the first option in the sub-menu but the remaining options are hidden behind the screen being displayed.  See the attached screen shot for an example.  

 

This is occurring on the ‘Welcome’ screen and any other screen/page I select.  And again, this just started occurring about a week or two ago – the site has been up since May of last year.

 

John

**Comment by bhadaway** [comment]
You're still on version 1.1.4; make sure to upgrade to 1.1.5.

**Comment by zman58tmh** [comment]
Bryan, just wanted to thank you for your help.  After upgrading to 1.1.5 and clearing the browser cache, the website is working as expected.

 

John
